services:
  - type: web
    name: forecast-lite0
    env: python
    pythonVersion: "3.11.4"
    buildCommand: >
      python3 -m pip install --upgrade pip setuptools wheel &&
      python3 -m pip install --no-cache-dir -r requirements.txt
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
