services:
  - type: web
    name: forecast-lite0
    env: docker
    dockerfilePath: ./Dockerfile
    # Render 會自動 build Dockerfile，無需額外 Build Command
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
