services:
  - type: web
    name: forecast-lite0
    env: python
    plan: free
    pythonVersion: "3.11"
    buildCommand: "python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
